create table if not exists public.market_signals (
  id bigint generated by default as identity primary key,
  signal_date date not null unique,
  direction text not null default 'neutral',
  confidence text not null default 'low',
  score integer not null default 0,
  summary text not null,
  brent_usd numeric(10, 2),
  usd_try numeric(10, 4),
  brent_try_index numeric(12, 2),
  brent_change_3d numeric(8, 2),
  usd_change_3d numeric(8, 2),
  index_change_3d numeric(8, 2),
  index_change_7d numeric(8, 2),
  signals jsonb not null default '[]'::jsonb,
  sources jsonb not null default '{}'::jsonb,
  calculated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.market_signals enable row level security;

grant select on public.market_signals to anon;
grant all on public.market_signals to service_role;
grant usage, select on sequence public.market_signals_id_seq to service_role;

drop policy if exists "market_signals_select_anon" on public.market_signals;

create policy "market_signals_select_anon"
on public.market_signals
for select
to anon
using (true);
