create table if not exists public.push_tokens (
  installation_id text primary key,
  expo_push_token text not null,
  platform text,
  app_version text,
  enabled boolean not null default true,
  daily_alerts boolean not null default true,
  city_alerts boolean not null default true,
  weekly_summary boolean not null default false,
  quiet_hours boolean not null default true,
  tracked_cities jsonb not null default '[]'::jsonb,
  tracked_fuels jsonb not null default '["Benzin", "Motorin", "LPG"]'::jsonb,
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.notification_logs (
  id bigint generated by default as identity primary key,
  sent_count integer not null default 0,
  change_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.push_tokens enable row level security;
alter table public.notification_logs enable row level security;

drop policy if exists "push_tokens_insert_anon" on public.push_tokens;
drop policy if exists "push_tokens_update_anon" on public.push_tokens;

create policy "push_tokens_insert_anon"
on public.push_tokens
for insert
to anon
with check (true);

create policy "push_tokens_update_anon"
on public.push_tokens
for update
to anon
using (true)
with check (true);
