create table if not exists public.push_tokens (
  installation_id text primary key,
  expo_push_token text not null,
  platform text,
  app_version text,
  enabled boolean not null default true,
  daily_alerts boolean not null default true,
  city_alerts boolean not null default true,
  weekly_summary boolean not null default false,
  quiet_hours boolean not null default true,
  tracked_cities jsonb not null default '[]'::jsonb,
  tracked_fuels jsonb not null default '["Benzin", "Motorin", "LPG"]'::jsonb,
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.notification_logs (
  id bigint generated by default as identity primary key,
  status text not null default 'sent',
  reason text,
  sent_count integer not null default 0,
  change_count integer not null default 0,
  token_count integer not null default 0,
  candidate_count integer not null default 0,
  skipped_quiet_count integer not null default 0,
  skipped_empty_token_count integer not null default 0,
  skipped_no_match_count integer not null default 0,
  error_message text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.notification_logs add column if not exists status text not null default 'sent';
alter table public.notification_logs add column if not exists reason text;
alter table public.notification_logs add column if not exists token_count integer not null default 0;
alter table public.notification_logs add column if not exists candidate_count integer not null default 0;
alter table public.notification_logs add column if not exists skipped_quiet_count integer not null default 0;
alter table public.notification_logs add column if not exists skipped_empty_token_count integer not null default 0;
alter table public.notification_logs add column if not exists skipped_no_match_count integer not null default 0;
alter table public.notification_logs add column if not exists error_message text;
alter table public.notification_logs add column if not exists details jsonb not null default '{}'::jsonb;

alter table public.push_tokens enable row level security;
alter table public.notification_logs enable row level security;

grant insert, update on public.push_tokens to anon;
grant all on public.push_tokens to service_role;
grant all on public.notification_logs to service_role;
grant usage, select on sequence public.notification_logs_id_seq to service_role;

drop policy if exists "push_tokens_insert_anon" on public.push_tokens;
drop policy if exists "push_tokens_update_anon" on public.push_tokens;

create policy "push_tokens_insert_anon"
on public.push_tokens
for insert
to anon
with check (true);

create policy "push_tokens_update_anon"
on public.push_tokens
for update
to anon
using (true)
with check (true);
