create table if not exists public.push_tokens (
  installation_id text primary key,
  expo_push_token text not null,
  platform text,
  app_version text,
  enabled boolean not null default true,
  daily_alerts boolean not null default true,
  city_alerts boolean not null default true,
  weekly_summary boolean not null default false,
  quiet_hours boolean not null default true,
  tracked_cities jsonb not null default '[]'::jsonb,
  tracked_fuels jsonb not null default '["Benzin", "Motorin", "LPG"]'::jsonb,
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.notification_logs (
  id bigint generated by default as identity primary key,
  status text not null default 'sent',
  reason text,
  sent_count integer not null default 0,
  change_count integer not null default 0,
  token_count integer not null default 0,
  candidate_count integer not null default 0,
  skipped_quiet_count integer not null default 0,
  skipped_empty_token_count integer not null default 0,
  skipped_no_match_count integer not null default 0,
  error_message text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.notification_logs add column if not exists status text not null default 'sent';
alter table public.notification_logs add column if not exists reason text;
alter table public.notification_logs add column if not exists token_count integer not null default 0;
alter table public.notification_logs add column if not exists candidate_count integer not null default 0;
alter table public.notification_logs add column if not exists skipped_quiet_count integer not null default 0;
alter table public.notification_logs add column if not exists skipped_empty_token_count integer not null default 0;
alter table public.notification_logs add column if not exists skipped_no_match_count integer not null default 0;
alter table public.notification_logs add column if not exists error_message text;
alter table public.notification_logs add column if not exists details jsonb not null default '{}'::jsonb;

alter table public.push_tokens enable row level security;
alter table public.notification_logs enable row level security;

grant all on public.push_tokens to service_role;
grant all on public.notification_logs to service_role;
grant usage, select on sequence public.notification_logs_id_seq to service_role;

revoke insert, update on public.push_tokens from anon, authenticated;

drop policy if exists "push_tokens_insert_anon" on public.push_tokens;
drop policy if exists "push_tokens_update_anon" on public.push_tokens;

create or replace function public.register_push_token(payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  installation_id_value text := trim(coalesce(payload ->> 'installation_id', ''));
  expo_push_token_value text := trim(coalesce(payload ->> 'expo_push_token', ''));
begin
  if length(installation_id_value) < 8 or length(expo_push_token_value) < 10 then
    raise exception 'Invalid push token registration payload';
  end if;

  insert into public.push_tokens (
    app_version,
    city_alerts,
    daily_alerts,
    enabled,
    expo_push_token,
    installation_id,
    last_seen_at,
    platform,
    quiet_hours,
    tracked_cities,
    tracked_fuels,
    updated_at,
    weekly_summary
  )
  values (
    nullif(payload ->> 'app_version', ''),
    coalesce((payload ->> 'city_alerts')::boolean, true),
    coalesce((payload ->> 'daily_alerts')::boolean, true),
    coalesce((payload ->> 'enabled')::boolean, true),
    expo_push_token_value,
    installation_id_value,
    coalesce((payload ->> 'last_seen_at')::timestamptz, now()),
    nullif(payload ->> 'platform', ''),
    coalesce((payload ->> 'quiet_hours')::boolean, true),
    coalesce(payload -> 'tracked_cities', '[]'::jsonb),
    coalesce(payload -> 'tracked_fuels', '["Benzin", "Motorin", "LPG"]'::jsonb),
    coalesce((payload ->> 'updated_at')::timestamptz, now()),
    coalesce((payload ->> 'weekly_summary')::boolean, false)
  )
  on conflict (installation_id) do update set
    app_version = excluded.app_version,
    city_alerts = excluded.city_alerts,
    daily_alerts = excluded.daily_alerts,
    enabled = excluded.enabled,
    expo_push_token = excluded.expo_push_token,
    last_seen_at = excluded.last_seen_at,
    platform = excluded.platform,
    quiet_hours = excluded.quiet_hours,
    tracked_cities = excluded.tracked_cities,
    tracked_fuels = excluded.tracked_fuels,
    updated_at = excluded.updated_at,
    weekly_summary = excluded.weekly_summary;
end;
$$;

revoke all on function public.register_push_token(jsonb) from public;
grant execute on function public.register_push_token(jsonb) to anon, authenticated;
